services:
  mongo:
    image: mongo:4.4
    command: --nojournal
  client:
    image: iot-isel/fiware-client
    ports:
      - "8081:8081"   
  orion:
    image: fiware/orion
    links:
      - mongo
      - client
    ports:
      - "10026:1026"
    command: -dbhost mongo
    environment:
      - TZ=Europe/Lisbon
  node-red:
    image: nodered/node-red:latest
    links:
      - orion
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/Lisbon